### ISSUE TITLE
[ERROR] 'REDItools' object has no attribute 'load_splicing_file'

### ISSUE THREAD

**Issue by gianfilippo** [BioinfoUNIBA/REDItools3#20]
Hi,

I am testing REDItools3, which I assume it has similar input requirements as its predecessors. I am running the folowing

python -m reditools analyze -t 20 -s 0 -mrl 50 -os 5 -q 20 -bq 20 -mbp 6 -Mbp 6 -e -r GRCh38.primary_assembly.genome.fa -o serial_RNA_table.tsv -sf gencode.v41.primary_assembly.annotation.splicesites.tsv -ss 4 deduped.bam

I am seeing the following error message 
[ERROR] 'REDItools' object has no attribute 'load_splicing_file'

Can you please help with it ?

Thanks

**Comment by ahanden** [comment]
Just saw your issue posted here. I'll look into it and get a reply up this week.

**Comment by gianfilippo** [comment]
thanks!
Could you also please clarify if I should still follow the Nature Protocol ? I mean, just replacing the original reditools in "Identification of all DNA–RNA variants" with REDItools3 .
Thanks

**Comment by ahanden** [comment]
I found the code issue with the splicing sites. I'll need to do some tests before publishing a fix, but will definitely be this week.

As for "Identification of all DNA–RNA variants", we actually don't an equivalent function in REDI3.

**Comment by gianfilippo** [comment]
Thanks. I am asking about the Nature protocol as I think I am a confused on how to run properly this analysis using version 2 or this version 3. 
In version 1, following the protocol for de novo analysis, one runs REDItoolDnaRna.py (RNA and DNA together) followed by a sequence steps of annotation, filtering, splitting, remapping, etc 
In version 2, RNA and DNA are separate steps, followed by annotate_with_DNA.py. Here some of the filtering, splitting and annotation and remapping done in version 1 are missing.
Version 3 seems similar to version 2.
I guess my question is why are those steps unnecessary now ? 
can you reproduce the same results of version 1 without those steps ?
Needless to say, I do not have much experience with calling editing events, and I am just trying to understand the approach here
Thanks

**Comment by gianfilippo** [comment]
On a side note,  GATK recommends splitting reads that contain Ns in their cigar string. You do not seem to use it. Did you look into it ?
Thanks

**Comment by BioinfoUNIBA** [comment]
Since REDItools is an empirical tool for RNA editing detection, the goal is to filter out errors and genomic variants that could interfere with downstream interpretations. So, the first step we suggest in the protocol is to use RNA and DNA to exclude potential SNPs. Since this function is not implemented in REDI2 and REDI3, you can still use both running two independent executions, one for your RNAseq and the second for your DNAseq. Then, you can detect AG and TC changes in your DNAseq and exclude such positions from your RNAseq. Unfortunately, we don't provide a script for this task but it should be easy using our AnnotateTable, proving a list of SNPs from your DNAseq. Once this step has been completed, you can annotate your sites according to the steps suggested in the protocol. About the GATK recommendation, I'm not sure it is a good suggestion. Splitting reads with Ns could be a solution if you align using splicing-unaware software. But the number of Ns should be compatible with the intron size. In general, I remove reads before the alignment step if they contain more than 2 Ns, but it is arbitrary. Then, a splicing-aware software is recommended.

**Comment by gianfilippo** [comment]
Thanks!
